sudo: required
services:
    - docker
before_install:
    - docker build -t swethafirst/docker-react -f Dockerfile.dev . 
script:
    - docker run swethafirst/docker-react npm run test -- --coverage      