sudo: required
services:
    - docker
before_install:
    - docker build -t snagubandi01/docker-react -f Dockerfile.dev . 
script:
    - docker run snagubandi01/docker-react npm run test -- --coverage      